'use server';
/**
 * @fileOverview An AI interview agent that provides adaptive questions based on the selected interview mode
 * and user responses, simulating a real-time interview experience.
 *
 * - adaptiveAiInterview - A function that handles the AI interview process.
 * - AdaptiveAIInterviewInput - The input type for the adaptiveAiInterview function.
 * - AdaptiveAIInterviewOutput - The return type for the adaptiveAiInterview function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const InterviewModeSchema = z.enum([
  'DSA',
  'HR',
  'Core CS',
  'System Design',
  'Resume-Based',
  'Company',
]);

const AIPersonalitySchema = z.enum([
  'Strict HR',
  'Friendly Mentor',
  'Corporate Manager',
]);

const AdaptiveAIInterviewInputSchema = z.object({
  interviewMode: InterviewModeSchema.describe(
    'The chosen interview mode (e.g., DSA, HR, Core CS, System Design, Resume-Based, Company).'
  ),
  aiPersonality: AIPersonalitySchema.optional().describe(
    'The personality of the AI interviewer (e.g., Strict HR, Friendly Mentor, Corporate Manager).' +
      ' If not provided, the AI will use a neutral professional tone.'
  ),
  previousQuestion: z
    .string()
    .optional()
    .describe('The question previously asked by the AI.'),
  userResponse: z
    .string()
    .optional()
    .describe('The user\u0027s current response to the AI\u0027s question.'),
});
export type AdaptiveAIInterviewInput = z.infer<
  typeof AdaptiveAIInterviewInputSchema
>;

const AdaptiveAIInterviewOutputSchema = z.object({
  aiQuestion: z.string().describe('The next question generated by the AI.'),
  sentimentFeedback: z
    .string()
    .optional()
    .describe(
      'Feedback on the user\u0027s sentiment based on their response, if available.'
    ),
  confidenceFeedback: z
    .string()
    .optional()
    .describe(
      'Feedback on the user\u0027s confidence level based on their response, if available.'
    ),
});
export type AdaptiveAIInterviewOutput = z.infer<
  typeof AdaptiveAIInterviewOutputSchema
>;

export async function adaptiveAiInterview(
  input: AdaptiveAIInterviewInput
): Promise<AdaptiveAIInterviewOutput> {
  return adaptiveAiInterviewFlow(input);
}

const adaptiveAiInterviewPrompt = ai.definePrompt({
  name: 'adaptiveAiInterviewPrompt',
  input: { schema: AdaptiveAIInterviewInputSchema },
  output: { schema: AdaptiveAIInterviewOutputSchema },
  prompt: `You are an AI interviewer for a technical interview simulator. Your goal is to ask questions relevant to the chosen interview mode and adapt your follow-up questions based on the user's response.
You must generate only one question at a time.

Interview Mode: {{{interviewMode}}}
{{#if aiPersonality}}
Your personality for this interview is: {{{aiPersonality}}}. Respond in a way that matches this personality.
{{else}}
Your personality is neutral professional. Respond in a way that matches this personality.
{{/if}}

{{#if previousQuestion}}
The previous question you asked was: "{{{previousQuestion}}}"
The user's response was: "{{{userResponse}}}"

Based on the user's response, ask a relevant follow-up question that either deepens the current topic, clarifies ambiguities, or moves to a related sub-topic if the current topic seems exhausted. Ensure the question is directly related to the interview mode.

{{#if userResponse}}
Analyze the user's response for its clarity and confidence. Provide a brief, constructive sentiment and confidence feedback. For example, if the user was unsure, suggest they articulate more clearly.
{{/if}}

{{else}}
Start the interview by asking an initial question relevant to the "{{{interviewMode}}}" interview mode.
{{/if}}

Your response should strictly be a JSON object conforming to the output schema.`,
});

const adaptiveAiInterviewFlow = ai.defineFlow(
  {
    name: 'adaptiveAiInterviewFlow',
    inputSchema: AdaptiveAIInterviewInputSchema,
    outputSchema: AdaptiveAIInterviewOutputSchema,
  },
  async (input) => {
    const { output } = await adaptiveAiInterviewPrompt(input);
    return output!;
  }
);
